### ISSUE TITLE
Spielfeld erstellungsklassse Java

### ISSUE THREAD

**Issue by pauleman1** [pauleman1/kniffeljava#14]
@julianwgit  erstell doch bitte nun die Klasse für Das Spielfeld, 

denke bitte an alle spieler 1 - 5
und wenn dus schaffst auch mit try und catch fehler abfangen

**Comment by pauleman1** [comment]
done

**Comment by pauleman1** [comment]
Player wird überarbeitet

**Comment by julianwgit** [comment]
check
